#SCC5871/MAI5025 - INTRODUÇÃO A REDES NEURAIS
# PROFA. ROSELI AP. FRANCELIN ROMERO
# Aula 02 - Exercício 02
### Multi_Layer Perceptrons
- REGRESSÃO <br>
- CLASSIFICADOR
c


# Exercicio 1 - REGRESSOR
Utilize o conjunto de dados utilizado no Exercício da Aula1: dados.txt

- Teste com 3 diferentes arquiteturas de redes multi-camadas (MLPs)
- Compare o erro MSE obtido com os modelos treinados com o erro MSE obtido com a regressão multivariada.


In [94]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Carrega os dados a partir do arquivo
data = pd.read_csv('dados.txt')

# Separa as features (X) do target (y)
X = data.iloc[:, :-1]  # Todas as colunas, exceto a última
y = data.iloc[:,-1:]   # Última coluna

# Normalizar os atributos entre 0 e 1
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Exemplo de exibição dos dados lidos
print("Dados de entrada (features):")
print(X_normalized)
print("\nDados de saída (target):")
print(y.head(3))

Dados de entrada (features):
[[0.81564501 0.9895288  0.40939597 ... 0.6424581  0.02739726 0.73032598]
 [0.23513266 0.14659686 0.58389262 ... 0.11173184 0.74815595 0.18768522]
 [0.62763038 0.97905759 0.71812081 ... 0.94972067 0.         1.        ]
 ...
 [0.23696249 0.33507853 0.46979866 ... 0.77653631 0.90200211 0.02403688]
 [0.8147301  0.71204188 0.22147651 ... 0.1452514  0.02739726 0.73032598]
 [0.21774931 0.12041885 0.63087248 ... 0.70949721 0.90200211 0.02403688]]

Dados de saída (target):
    CO
0  7.1
1  5.9
2  9.6


In [95]:
from sklearn.model_selection import train_test_split

# Divide os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)

# Exemplo de exibição dos conjuntos de treino e teste
print("Conjunto de treino:")
print("Features (X_train):")
print(X_train)
print("Target (y_train):")
print(y_train)

print("\nConjunto de teste:")
print("Features (X_test):")
print(X_test)
print("Target (y_test):")
print(y_test)


Conjunto de treino:
Features (X_train):
[[0.64913083 0.43455497 0.43624161 ... 0.76536313 0.02739726 0.73032598]
 [0.84903934 0.82722513 0.25503356 ... 0.67597765 0.02739726 0.73032598]
 [0.41857274 0.20418848 0.1409396  ... 0.68715084 0.09694415 0.82219295]
 ...
 [0.20036597 0.14659686 0.44295302 ... 0.02793296 0.74394099 0.18768522]
 [0.7273559  0.7382199  0.44966443 ... 0.81005587 0.02739726 0.73032598]
 [0.18755718 0.27748691 0.54362416 ... 0.83240223 0.90200211 0.02403688]]
Target (y_train):
       CO
424  12.1
113   4.8
101   6.4
57    2.8
462   5.4
..    ...
106   4.9
270   3.7
348   4.4
435   6.7
102   3.9

[371 rows x 1 columns]

Conjunto de teste:
Features (X_test):
[[0.10978957 0.14659686 0.69127517 ... 0.80446927 0.90200211 0.02403688]
 [0.41674291 0.52879581 0.17449664 ... 0.11731844 0.13645943 0.        ]
 [0.22232388 0.28795812 0.03355705 ... 0.36871508 0.58324552 0.06717155]
 ...
 [0.22049405 0.31413613 0.03355705 ... 0.87150838 0.69546891 0.03226869]
 [0.8115279  0.790

In [108]:
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

# Inicialização das arquiteturas de MLPs
mlp1 = MLPRegressor(hidden_layer_sizes=(10,), activation='identity', solver='lbfgs', max_iter=500, random_state=42)
mlp2 = MLPRegressor(hidden_layer_sizes=(5,), activation='relu', solver='lbfgs', max_iter=500, random_state=42)
mlp3 = MLPRegressor(hidden_layer_sizes=(1,), activation='logistic', solver='lbfgs', max_iter=500, random_state=42)

# Treinamento das MLPs
mlp1.fit(X_train, y_train)
mlp2.fit(X_train, y_train)
mlp3.fit(X_train, y_train)

# Previsões das MLPs nos dados de teste
mlp1_pred = mlp1.predict(X_test)
mlp2_pred = mlp2.predict(X_test)
mlp3_pred = mlp3.predict(X_test)

# Inicialização e treinamento da regressão multivariada
regression = LinearRegression()
regression.fit(X_train, y_train)

# Previsão da regressão multivariada nos dados de teste
regression_pred = regression.predict(X_test)

# Cálculo do erro MSE para cada modelo
mlp1_mse = mean_squared_error(y_test, mlp1_pred)
mlp2_mse = mean_squared_error(y_test, mlp2_pred)
mlp3_mse = mean_squared_error(y_test, mlp3_pred)
regression_mse = mean_squared_error(y_test, regression_pred)

# Exibição dos resultados
print("Erro MSE da MLP1:", mlp1_mse)
print("Erro MSE da MLP2:", mlp2_mse)
print("Erro MSE da MLP3:", mlp3_mse)
print("Erro MSE da regressão multivariada:", regression_mse)


Erro MSE da MLP1: 4.139815497653451
Erro MSE da MLP2: 3.8348696534802844
Erro MSE da MLP3: 5.1451554951987495
Erro MSE da regressão multivariada: 4.139931863950951


C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1623: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1623: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to conve

Após analisar diversas combinações, deixamos as 3 acima como exemplos, pois alcançaram resultados próximos à regressão linear, sendo que a primeira teve um resultado muito semelhante, a segunda foi ligeiramente melhor e a terceira ficou um pouco acima.

# Exercicio 2 - CLASSIFICADOR

## Multilayer Perceptron para classificação do dataset Wine
Neste exercício utilizaremos a base de dados Wine, que consiste em 178 exemplos de dimensionalidade 13, separados em 3 classes. Os atributos dessa base de dados não estão normalizados, apresentando intervalos variados de valores.

- Carregue a base de dados wine e normalize entre 0 e 1 o valor dos seus atributos

In [109]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler

# Carregar a base de dados wine
wine = load_wine()

# Obter as features (X) e os targets (y)
X = wine.data
y = wine.target

# Normalizar os atributos entre 0 e 1
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Exemplo de exibição dos dados normalizados
print("Dados normalizados:")
print(X_normalized)


Dados normalizados:
[[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]]


---
- Agora divida a base em conjunto de teste e treino. Utilize 20% da base para teste e 80% para treino.

In [110]:
from sklearn.model_selection import train_test_split

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)

# Exemplo de exibição dos conjuntos de treino e teste
print("Conjunto de treino:")
print("Features de treino (X_train):")
print(X_train)
print("Targets de treino (y_train):")
print(y_train)

print("\nConjunto de teste:")
print("Features de teste (X_test):")
print(X_test)
print("Targets de teste (y_test):")
print(y_test)


Conjunto de treino:
Features de treino (X_train):
[[0.87105263 0.18577075 0.71657754 ... 0.07317073 0.25274725 0.2724679 ]
 [0.39473684 0.94268775 0.68449198 ... 0.27642276 0.15384615 0.16904422]
 [0.35263158 0.06521739 0.39572193 ... 0.45528455 0.54945055 0.2724679 ]
 ...
 [0.88157895 0.22332016 0.54545455 ... 0.58536585 0.63369963 0.90513552]
 [0.43684211 0.15612648 0.48128342 ... 0.3902439  0.28937729 0.15477889]
 [0.34473684 0.33794466 0.58823529 ... 0.2601626  0.77289377 0.11412268]]
Targets de treino (y_train):
[2 2 1 2 0 1 1 1 2 0 1 1 2 0 1 0 0 2 2 1 1 0 1 0 2 1 1 2 0 0 0 2 0 0 1 2 1
 0 2 1 0 2 1 1 0 1 0 0 1 0 0 2 1 1 1 0 1 1 1 2 2 0 1 2 2 1 1 0 1 2 2 1 2 1
 1 1 0 0 2 0 2 0 0 1 1 0 0 0 1 0 1 2 1 1 1 2 2 1 0 0 1 2 2 0 1 2 2 2 2 1 0
 1 0 2 0 0 1 0 0 2 1 0 2 2 0 0 2 2 2 1 1 1 1 1 1 2 0 1 1 0 1 1]

Conjunto de teste:
Features de teste (X_test):
[[0.68684211 0.46640316 0.64171123 0.2371134  0.5        0.59310345
  0.56751055 0.0754717  0.39432177 0.32593857 0.3902439  0.76556777
  0.

---
- Treine 3 classificadores MLP (com `solver='sgd'`), variando o número de neurônios na camada escondida. Reporte o score dos classificadores nos conjuntos de treino e teste.
  - Parâmetros para  alterar: hidden_layer_sizes, max_iter,  tol, learning_rate_init

In [111]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV


# Definir o espaço de busca dos parâmetros
param_grid = {
    'hidden_layer_sizes': [(10,), (50,), (100,)],
    'max_iter': [200, 500, 1000],
    'tol': [1e-3, 1e-4, 1e-5],
    'learning_rate_init': [0.001, 0.01, 0.1]
}

# Criar o objeto GridSearchCV
grid_search = GridSearchCV(
    estimator=MLPClassifier(hidden_layer_sizes=20, solver='sgd', alpha=0.001,learning_rate='adaptive', max_iter=1000),
    param_grid=param_grid,
    cv=5
)

# Realizar a busca pelos melhores hiperparâmetros
grid_search.fit(X_train, y_train)

# Obter os melhores hiperparâmetros encontrados
best_params = grid_search.best_params_

print("Melhores hiperparâmetros:")
for param, value in best_params.items():
    print(f"{param}: {value}")

# Avaliar o score do modelo com os melhores hiperparâmetros nos conjuntos de treino e teste
train_score = grid_search.score(X_train, y_train)
test_score = grid_search.score(X_test, y_test)

print("\nScore de treino com os melhores hiperparâmetros:", train_score)
print("Score de teste com os melhores hiperparâmetros:", test_score)



C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\gabri\A

Melhores hiperparâmetros:
hidden_layer_sizes: (10,)
learning_rate_init: 0.01
max_iter: 500
tol: 0.0001

Score de treino com os melhores hiperparâmetros: 0.9859154929577465
Score de teste com os melhores hiperparâmetros: 1.0


C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


---
- Selecione uma amostra pequena de tamanho 10 do conjunto de testes. Selecione o classificador que apresentou maior acurácia no conjunto de testes e calcule, para cada elemento da amostra, a classe esperada, a classe obtida e a probabilidade estimada de cada classe

In [112]:
# Melhor modelo com os hiperparâmetros selecionados
best_model = MLPClassifier(hidden_layer_sizes=(10,), learning_rate_init=0.01, max_iter=500, tol=0.0001)
best_model.fit(X_train, y_train)

# Selecionar uma amostra de tamanho 10 do conjunto de testes
sample_size = 10
X_sample = X_test[:sample_size]
y_sample = y_test[:sample_size]

# Calcular a classe esperada, a classe obtida e a probabilidade estimada de cada classe para cada elemento da amostra
expected_classes = y_sample
predicted_classes = best_model.predict(X_sample)
predicted_probabilities = best_model.predict_proba(X_sample)

# Exibir os resultados para cada elemento da amostra
for i in range(sample_size):
    print(f"Elemento {i+1}:")
    print("Classe esperada:", expected_classes[i])
    print("Classe obtida:", predicted_classes[i])
    print("Probabilidade estimada de cada classe:")
    for j, prob in enumerate(predicted_probabilities[i]):
        print(f"Classe {j}: {prob}")
    print("------------------------")

Elemento 1:
Classe esperada: 0
Classe obtida: 0
Probabilidade estimada de cada classe:
Classe 0: 0.9999362816587988
Classe 1: 4.603038209870515e-05
Classe 2: 1.7687959102530755e-05
------------------------
Elemento 2:
Classe esperada: 0
Classe obtida: 0
Probabilidade estimada de cada classe:
Classe 0: 0.9997299053070057
Classe 1: 1.066026736330486e-05
Classe 2: 0.00025943442563098907
------------------------
Elemento 3:
Classe esperada: 2
Classe obtida: 2
Probabilidade estimada de cada classe:
Classe 0: 0.002302845481133202
Classe 1: 0.0040876846115830145
Classe 2: 0.9936094699072837
------------------------
Elemento 4:
Classe esperada: 0
Classe obtida: 0
Probabilidade estimada de cada classe:
Classe 0: 0.9998334320390703
Classe 1: 0.00015667860681213208
Classe 2: 9.889354117541567e-06
------------------------
Elemento 5:
Classe esperada: 1
Classe obtida: 1
Probabilidade estimada de cada classe:
Classe 0: 0.00018650828122063643
Classe 1: 0.9998109164373189
Classe 2: 2.5752814604538583e

---
- Agora sobre a mesma amostra escolhida anteriormente, selecione o classificador que apresentou menor acurácia no conjunto de testes e calcule, para cada elemento da amostra, a classe esperada, a classe obtida e a probabilidade esperada de cada classe.

In [113]:
# Pior modelo com os hiperparâmetros selecionados
worst_model = MLPClassifier()
worst_model.fit(X_train, y_train)


# Calcular a classe esperada, a classe obtida e a probabilidade estimada de cada classe para cada elemento da amostra
expected_classes = y_sample
predicted_classes = worst_model.predict(X_sample)
predicted_probabilities = worst_model.predict_proba(X_sample)

# Exibir os resultados para cada elemento da amostra
for i in range(sample_size):
    print(f"Elemento {i+1}:")
    print("Classe esperada:", expected_classes[i])
    print("Classe obtida:", predicted_classes[i])
    print("Probabilidade estimada de cada classe:")
    for j, prob in enumerate(predicted_probabilities[i]):
        print(f"Classe {j}: {prob}")
    print("------------------------")

Elemento 1:
Classe esperada: 0
Classe obtida: 0
Probabilidade estimada de cada classe:
Classe 0: 0.9631681609260383
Classe 1: 0.02912836185938061
Classe 2: 0.007703477214581107
------------------------
Elemento 2:
Classe esperada: 0
Classe obtida: 0
Probabilidade estimada de cada classe:
Classe 0: 0.9312661616127099
Classe 1: 0.025421021862405576
Classe 2: 0.04331281652488456
------------------------
Elemento 3:
Classe esperada: 2
Classe obtida: 2
Probabilidade estimada de cada classe:
Classe 0: 0.03982112406477053
Classe 1: 0.1397860253053091
Classe 2: 0.8203928506299203
------------------------
Elemento 4:
Classe esperada: 0
Classe obtida: 0
Probabilidade estimada de cada classe:
Classe 0: 0.9048126071574273
Classe 1: 0.08793995597736064
Classe 2: 0.007247436865212077
------------------------
Elemento 5:
Classe esperada: 1
Classe obtida: 1
Probabilidade estimada de cada classe:
Classe 0: 0.06380890046258923
Classe 1: 0.9321512911842971
Classe 2: 0.004039808353113671
-----------------

C:\Users\gabri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(




---

- Faça uma análise das probabilidades calculadas por cada classificador nos exemplos corretos e relacione-as com a 'qualidade' dos mesmos.

O melhor classificador sempre obtem uma consistência maior nas probabilidades, isto é, tende a atribuir probabilidades próximas de 0 ou 1 para a classe correta nos exemplos corretos. 

Por exemplo, o pior classificador exibiu os seguintes resultados para um dos elementos do conjunto de tamanho 10 selecionado:

Elemento 10:
Classe esperada: 2
Classe obtida: 2
Probabilidade estimada de cada classe:

Classe 0: 0.14512187957975095

Classe 1: 0.09876354639919084

Classe 2: 0.7561145740210582

------------------------

Ou seja, considera que é possível que haja ~14% de chance de ser da classe 0, quando na verdade é a clsse 2, em que se atribuiu probabilidade de ~76%. Para o mesmo exemplo o melhor classificador atribuiu ~98% para a classe correta, uma diferença de ~22% de certeza.


---
- Calcule, usando 10-fold cross-validation, a acurácia média da melhor configuração de classificador que você utilizou e seu desvio padrão

In [114]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

# Realizar 10-fold cross-validation e calcular a acurácia média e o desvio padrão
scores = cross_val_score(best_model, X_normalized, y, cv=10)

# Exibir a acurácia média e o desvio padrão
mean_accuracy = scores.mean()
std_accuracy = scores.std()

print("Acurácia média:", mean_accuracy)
print("Desvio padrão:", std_accuracy)

Acurácia média: 0.9777777777777779
Desvio padrão: 0.027216552697590882
